# Dependabot configuration for create-tui
# Keeps all template dependencies and main project dependencies up to date
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Main project dependencies (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "root"

  # CLI package dependencies
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "cli"

  # Core template dependencies
  - package-ecosystem: "npm"
    directory: "/packages/templates/core"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "template-core"

  # React template dependencies
  - package-ecosystem: "npm"
    directory: "/packages/templates/react"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "template-react"

  # Solid template dependencies
  - package-ecosystem: "npm"
    directory: "/packages/templates/solid"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "template-solid"

  # Vue template dependencies
  - package-ecosystem: "npm"
    directory: "/packages/templates/vue"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "template-vue"
